### ISSUE TITLE
The seasonal mapping in the code and the text is different from what is there in readme.txt

### ISSUE THREAD

**Issue by pradeepssundaram** [PacktWorkshops/The-Data-Analysis-Workshop#9]
In the readme.txt the following is the mapping for season : season (1:springer, 2:summer, 3:fall, 4:winter)
. However in the python code the mapping is :seasons_mapping = {1: 'winter', 2: 'spring', 3: 'summer', 4: 'fall'}.

Which one is accurate.

**Comment by PacktSupport** [comment]
Hello Pradeep, thank you very much for pointing this out! We will check this bit with the subject experts and make the required changes as soon as we can.

**Comment by kkt86** [comment]
Inconsistencies have been fixed in readme file
